global using System;
global using System.Collections.Generic;
global using System.CommandLine;
global using System.CommandLine.Invocation;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Threading.Tasks;