name: ci

on:
  push:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      PreRelease:
        description: "PreRelease"
        required: false

jobs:
  ubuntu-24_04:
    name: ubuntu-24_04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
      - name: NuGet Login
        uses: NuGet/login@v1
        with:
          user: my-nuget-username
      - name: "Build, test, pack"
        run: ./src/build.sh
        env:
          PreRelease: ${{ github.event.inputs.PreRelease }}
      - name: "Publish: package"
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: artifacts/package
